library(stringr)
x <- c('hii','hello123','mrng')
# str_length(x)
# str_c(x,collapse=",")
# str_sub(x,1,2)
#str_subset(x,"[er]")
# str_count(x,"[el]")
# str_detect(x,"[el]")
# str_locate(x,"[el]")
# str_extract(x,"el")

# str_replace(x,"hello","good")
#str_replaceall("hello123","\\d+","world")
# str_match(x,Pattern='oo')
# str_pad('123',width=5,side=left,pad='0' )
#str_to_lower(x)
# str_to_upper(x)

y= c('  r  ','   hii')
# str_trim(y)
# str_to_title(y)
# str_dup(x,4)
# str_ends(x,"g")
str_equal('rain','RAIN',locale='en',ignore_case=TRUE)
